# Generated by Django 4.0.4 on 2022-04-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_description_promotions_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
